/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedFilmesRouteImport } from './routes/_authenticated/filmes'
import { Route as AuthenticatedGerenciarPerfisRouteImport } from './routes/_authenticated/gerenciar-perfis'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMinhaListaRouteImport } from './routes/_authenticated/minha-lista'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedReelsRouteImport } from './routes/_authenticated/reels'
import { Route as AuthenticatedSeriesRouteImport } from './routes/_authenticated/series'
import { Route as AuthenticatedEditarPerfilIdRouteImport } from './routes/_authenticated/editar-perfil.$id'
import { Route as AuthenticatedAssistirTipoIdRouteImport } from './routes/_authenticated/assistir.$tipo.$id'
import { Route as AuthenticatedTituloTipoIdRouteImport } from './routes/_authenticated/titulo.$tipo.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilmesRoute = AuthenticatedFilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGerenciarPerfisRoute =
  AuthenticatedGerenciarPerfisRouteImport.update({
    id: '/gerenciar-perfis',
    path: '/gerenciar-perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaListaRoute = AuthenticatedMinhaListaRouteImport.update({
  id: '/minha-lista',
  path: '/minha-lista',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReelsRoute = AuthenticatedReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeriesRoute = AuthenticatedSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditarPerfilIdRoute =
  AuthenticatedEditarPerfilIdRouteImport.update({
    id: '/editar-perfil/$id',
    path: '/editar-perfil/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistirTipoIdRoute =
  AuthenticatedAssistirTipoIdRouteImport.update({
    id: '/assistir/$tipo/$id',
    path: '/assistir/$tipo/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTituloTipoIdRoute =
  AuthenticatedTituloTipoIdRouteImport.update({
    id: '/titulo/$tipo/$id',
    path: '/titulo/$tipo/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/gerenciar-perfis': typeof AuthenticatedGerenciarPerfisRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/minha-lista': typeof AuthenticatedMinhaListaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/editar-perfil/$id': typeof AuthenticatedEditarPerfilIdRoute
  '/assistir/$tipo/$id': typeof AuthenticatedAssistirTipoIdRoute
  '/titulo/$tipo/$id': typeof AuthenticatedTituloTipoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conta': typeof AuthenticatedContaRoute
  '/filmes': typeof AuthenticatedFilmesRoute
  '/gerenciar-perfis': typeof AuthenticatedGerenciarPerfisRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/minha-lista': typeof AuthenticatedMinhaListaRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/reels': typeof AuthenticatedReelsRoute
  '/series': typeof AuthenticatedSeriesRoute
  '/editar-perfil/$id': typeof AuthenticatedEditarPerfilIdRoute
  '/assistir/$tipo/$id': typeof AuthenticatedAssistirTipoIdRoute
  '/titulo/$tipo/$id': typeof AuthenticatedTituloTipoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/filmes': typeof AuthenticatedFilmesRoute
  '/_authenticated/gerenciar-perfis': typeof AuthenticatedGerenciarPerfisRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/minha-lista': typeof AuthenticatedMinhaListaRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/reels': typeof AuthenticatedReelsRoute
  '/_authenticated/series': typeof AuthenticatedSeriesRoute
  '/_authenticated/editar-perfil/$id': typeof AuthenticatedEditarPerfilIdRoute
  '/_authenticated/assistir/$tipo/$id': typeof AuthenticatedAssistirTipoIdRoute
  '/_authenticated/titulo/$tipo/$id': typeof AuthenticatedTituloTipoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/busca'
    | '/configuracoes'
    | '/conta'
    | '/filmes'
    | '/gerenciar-perfis'
    | '/inicio'
    | '/minha-lista'
    | '/perfis'
    | '/reels'
    | '/series'
    | '/editar-perfil/$id'
    | '/assistir/$tipo/$id'
    | '/titulo/$tipo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/busca'
    | '/configuracoes'
    | '/conta'
    | '/filmes'
    | '/gerenciar-perfis'
    | '/inicio'
    | '/minha-lista'
    | '/perfis'
    | '/reels'
    | '/series'
    | '/editar-perfil/$id'
    | '/assistir/$tipo/$id'
    | '/titulo/$tipo/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/busca'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conta'
    | '/_authenticated/filmes'
    | '/_authenticated/gerenciar-perfis'
    | '/_authenticated/inicio'
    | '/_authenticated/minha-lista'
    | '/_authenticated/perfis'
    | '/_authenticated/reels'
    | '/_authenticated/series'
    | '/_authenticated/editar-perfil/$id'
    | '/_authenticated/assistir/$tipo/$id'
    | '/_authenticated/titulo/$tipo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filmes': {
      id: '/_authenticated/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof AuthenticatedFilmesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gerenciar-perfis': {
      id: '/_authenticated/gerenciar-perfis'
      path: '/gerenciar-perfis'
      fullPath: '/gerenciar-perfis'
      preLoaderRoute: typeof AuthenticatedGerenciarPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-lista': {
      id: '/_authenticated/minha-lista'
      path: '/minha-lista'
      fullPath: '/minha-lista'
      preLoaderRoute: typeof AuthenticatedMinhaListaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reels': {
      id: '/_authenticated/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AuthenticatedReelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/series': {
      id: '/_authenticated/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AuthenticatedSeriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editar-perfil/$id': {
      id: '/_authenticated/editar-perfil/$id'
      path: '/editar-perfil/$id'
      fullPath: '/editar-perfil/$id'
      preLoaderRoute: typeof AuthenticatedEditarPerfilIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistir/$tipo/$id': {
      id: '/_authenticated/assistir/$tipo/$id'
      path: '/assistir/$tipo/$id'
      fullPath: '/assistir/$tipo/$id'
      preLoaderRoute: typeof AuthenticatedAssistirTipoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/titulo/$tipo/$id': {
      id: '/_authenticated/titulo/$tipo/$id'
      path: '/titulo/$tipo/$id'
      fullPath: '/titulo/$tipo/$id'
      preLoaderRoute: typeof AuthenticatedTituloTipoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFilmesRoute: typeof AuthenticatedFilmesRoute
  AuthenticatedGerenciarPerfisRoute: typeof AuthenticatedGerenciarPerfisRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMinhaListaRoute: typeof AuthenticatedMinhaListaRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedReelsRoute: typeof AuthenticatedReelsRoute
  AuthenticatedSeriesRoute: typeof AuthenticatedSeriesRoute
  AuthenticatedEditarPerfilIdRoute: typeof AuthenticatedEditarPerfilIdRoute
  AuthenticatedAssistirTipoIdRoute: typeof AuthenticatedAssistirTipoIdRoute
  AuthenticatedTituloTipoIdRoute: typeof AuthenticatedTituloTipoIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFilmesRoute: AuthenticatedFilmesRoute,
  AuthenticatedGerenciarPerfisRoute: AuthenticatedGerenciarPerfisRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMinhaListaRoute: AuthenticatedMinhaListaRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedReelsRoute: AuthenticatedReelsRoute,
  AuthenticatedSeriesRoute: AuthenticatedSeriesRoute,
  AuthenticatedEditarPerfilIdRoute: AuthenticatedEditarPerfilIdRoute,
  AuthenticatedAssistirTipoIdRoute: AuthenticatedAssistirTipoIdRoute,
  AuthenticatedTituloTipoIdRoute: AuthenticatedTituloTipoIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
